FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/Services/LoggingService/Volvo.Service.Logging.API.csproj", "src/Services/LoggingService/"]
RUN dotnet restore "src/Services/LoggingService/Volvo.Service.Logging.API.csproj"

COPY src/Services/LoggingService/ ./src/Services/LoggingService/
WORKDIR "/src/Services/LoggingService"
RUN dotnet build "Volvo.Service.Logging.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Volvo.Service.Logging.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LoggingService.dll"]